### ISSUE TITLE
AboutFragment: FATAL EXCEPTION

### ISSUE THREAD

**Issue by adrcotfas** [daniel-stoneuk/material-about-library#102]
Hi,

I'm getting the following exception when starting the AboutFragment containing any cards built in `getMaterialAboutList` as in the guide.

Am I missing something?
Thanks!

```
2020-02-16 05:42:51.400 28256-28256/xyz.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xyz.myapp, PID: 28256
    android.view.InflateException: Binary XML file line #32 in xyz.myapp:layout/mal_material_about_list_card: Binary XML file line #32 in xyz.myapp:layout/mal_material_about_list_card: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #32 in xyz.myapp:layout/mal_material_about_list_card: Error inflating class TextView
    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:596)
        at android.widget.TextView.readTextAppearance(TextView.java:3967)
        at android.widget.TextView.<init>(TextView.java:1027)
        at android.widget.TextView.<init>(TextView.java:968)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.danielstone.materialaboutlibrary.adapters.MaterialAboutListAdapter.onCreateViewHolder(MaterialAboutListAdapter.java:48)
        at com.danielstone.materialaboutlibrary.adapters.MaterialAboutListAdapter.onCreateViewHolder(MaterialAboutListAdapter.java:25)
```

BTW, I'm using the Navigation component with a single `AppCompatActivity` and fragments `FragmentContainerView`.

**Comment by daniel-stoneuk** [comment]
Hi, were you able to sort this out?

**Comment by adrcotfas** [comment]
No.

**Comment by daniel-stoneuk** [comment]
Could you please try version 3.0.0 of the library and let me know how it goes. Cheers
