### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by AxelCC** [daniel-stoneuk/material-about-library#92]
I try to implement this library to my project, i've followed all the step but when I run my project get me a NoClassDefFoundError

12-01 09:05:53.760 E/AndroidRuntime(25347): java.lang.NoClassDefFoundError: com.danielstone.materialaboutlibrary.adapters.MaterialAboutListAdapter$1
12-01 09:05:53.760 E/AndroidRuntime(25347): 	at com.danielstone.materialaboutlibrary.adapters.MaterialAboutListAdapter.<clinit>(MaterialAboutListAdapter.java:141)
12-01 09:05:53.760 E/AndroidRuntime(25347): 	at com.danielstone.materialaboutlibrary.MaterialAboutActivity.initViews(MaterialAboutActivity.java:88)
12-01 09:05:53.760 E/AndroidRuntime(25347): 	at com.danielstone.materialaboutlibrary.MaterialAboutActivity.onCreate(MaterialAboutActivity.java:55)

I hope someine can help me

**Comment by daniel-stoneuk** [comment]
More information please!

**Comment by AxelCC** [comment]
I've update the comment

**Comment by daniel-stoneuk** [comment]
Thanks. Could you leave a copy of your build.gradle here as well so that we can check if there are any issues with setup.

**Comment by AxelCC** [comment]
Here is it
[build.txt](https://github.com/daniel-stoneuk/material-about-library/files/2635938/build.txt)

**Comment by daniel-stoneuk** [comment]
A few things:

* Why is your compileSdkVersion 21?
* Have you tried updating to AndroidX and using the latest release of the library?

**Comment by AxelCC** [comment]
I'm using AIDE for compile my projects
Yes, but when i use the latest version I have problems with AndroidX libraries

**Comment by AxelCC** [comment]
Can I use version 2.2.5 with new layout design ?

**Comment by daniel-stoneuk** [comment]
Nope, but it looks very similar. 

Can you confirm that it doesn't work when you change all the v25 support libraries to 28.0.0 https://developer.android.com/topic/libraries/support-library/revisions

**Comment by AxelCC** [comment]
Yep, it does not work

**Comment by AxelCC** [comment]
I try to use 2.4.0support library version but I get error that can not found dependency

**Comment by daniel-stoneuk** [comment]
Closing due to inactivity
